### ISSUE TITLE
ctl+w

### ISSUE THREAD

**Issue by Whyounes** [xavi-/sublime-maybs-quit#4]
when you close all files with (ctl+w), if there is no file left to close ST quit, how can i get a confirmation for this too?

**Comment by xavi-** [comment]
Hmm, I'm not sure if there's anything that can be done about that.  Have you tried setting `close_windows_when_empty` to `false` in your sublime settings?  Perhaps that'll have effect you're looking for?

**Comment by Whyounes** [comment]
It didn't do anything!!!

**Comment by xavi-** [comment]
Hmm, which operating system are you using?

If you're using OSX you may have to specify the setting in the User
Settings instead of Default Settings.

**Comment by Whyounes** [comment]
I use linux OpenSuse13 x64, i tested it on the User settings but didn't work.

**Comment by xavi-** [comment]
So I tried a couple of things and it seems like the best thing to do is to add a new command called `close_gaurd`.  By default it's unused, but you can enable it by adding this keyboard shortcut:

``` json
{ "keys": ["ctrl+w"], "command": "close_guard" }
```

Keep in mind that I just pushed the change, so you may have to quit and reopen sublime to see the update.  Let me know if this was what you were looking for.

**Comment by Whyounes** [comment]
it worked, but it ask's me if i want to quit even if there is an opened tab!!

**Comment by Whyounes** [comment]
I think you should update the window.views test and add key bindings

**Comment by xavi-** [comment]
You're right.  The option to quit is quite silly so I removed it.  As well as the option to close the view, since often times that's the same as closing the window.

At this point I don't think I should enable it by default since it's some what unusual.
